### PR TITLE
Add request dependency to resolve security issue

### PR DESCRIPTION
**Pull request by egyptianbman**
node-gyp@3 is pulling in an older version of request which is pulling in
(through other dependencies) hapijs/hoek version 2.16.3 which has a
security vulnerability. This commit requires a newer version of request
which forces npm to select a more recent version of hoek.

### CODE REVIEW

**Comment by egyptianbman** [comment]
I need to run some tests with this. I'll do so tonight.

**Comment by sennevb** [comment]
image
added these change to my package.json of my testserver running, npm audit still making fuzz about hoek

**Comment by nettts** [comment]
@egyptianbman has you reviewed @sennevb comment?

**Comment by egyptianbman** [comment]
I saw it. I also noticed that the package.lock doesn't seem to remove the issue. I'll come back to this soon unless someone else finds a solution before me.

**Pull request closed without merging**
